import type { EventLogEntry } from "./app-events.ts";
import type { CompactionStatus } from "./app-tool-stream.ts";
import type { DevicePairingList } from "./controllers/devices.ts";
import type { ExecApprovalRequest } from "./controllers/exec-approval.ts";
import type { ExecApprovalsFile, ExecApprovalsSnapshot } from "./controllers/exec-approvals.ts";
import type { SkillMessage } from "./controllers/skills.ts";
import type { GatewayBrowserClient, GatewayHelloOk } from "./gateway.ts";
import type { Tab } from "./navigation.ts";
import type { UiSettings } from "./storage.ts";
import type { ThemeTransitionContext } from "./theme-transition.ts";
import type { ThemeMode } from "./theme.ts";
import type {
  AgentsListResult,
  AgentsFilesListResult,
  AgentIdentityResult,
  ChannelsStatusSnapshot,
  ConfigSnapshot,
  ConfigUiHints,
  CronJob,
  CronRunLogEntry,
  CronStatus,
  HealthSnapshot,
  LogEntry,
  LogLevel,
  NostrProfile,
  PresenceEntry,
  SessionsUsageResult,
  CostUsageSummary,
  SessionUsageTimeSeries,
  SessionsListResult,
  SkillStatusReport,
  StatusSummary,
} from "./types.ts";
import type { ChatAttachment, ChatQueueItem, CronFormState } from "./ui-types.ts";
import type { NostrProfileFormState } from "./views/channels.nostr-profile-form.ts";
import type { NativeDialogModel } from "./views/native-dialog-overlay.ts";
import type { SessionLogEntry } from "./views/usage.ts";

export type AppViewState = {
  settings: UiSettings;
  password: string;
  tab: Tab;
  onboarding: boolean;
  basePath: string;
  connected: boolean;
  theme: ThemeMode;
  themeResolved: "light" | "dark";
  hello: GatewayHelloOk | null;
  lastError: string | null;
  eventLog: EventLogEntry[];
  assistantName: string;
  assistantAvatar: string | null;
  assistantAgentId: string | null;
  sessionKey: string;
  chatLoading: boolean;
  chatSending: boolean;
  chatMessage: string;
  chatAttachments: ChatAttachment[];
  chatMessages: unknown[];
  chatToolMessages: unknown[];
  chatStream: string | null;
  chatStreamStartedAt: number | null;
  chatRunId: string | null;
  compactionStatus: CompactionStatus | null;
  chatAvatarUrl: string | null;
  chatThinkingLevel: string | null;
  chatModelRef: string | null;
  chatQueue: ChatQueueItem[];
  nodesLoading: boolean;
  nodes: Array<Record<string, unknown>>;
  chatNewMessagesBelow: boolean;
  chatConversationOnly: boolean;
  sidebarOpen: boolean;
  sidebarContent: string | null;
  sidebarError: string | null;
  splitRatio: number;
  scrollToBottom: () => void;
  devicesLoading: boolean;
  devicesError: string | null;
  devicesList: DevicePairingList | null;
  execApprovalsLoading: boolean;
  execApprovalsSaving: boolean;
  execApprovalsDirty: boolean;
  execApprovalsSnapshot: ExecApprovalsSnapshot | null;
  execApprovalsForm: ExecApprovalsFile | null;
  execApprovalsSelectedAgent: string | null;
  execApprovalsTarget: "gateway" | "node";
  execApprovalsTargetNodeId: string | null;
  execApprovalQueue: ExecApprovalRequest[];
  execApprovalBusy: boolean;
  execApprovalError: string | null;
  pendingGatewayUrl: string | null;
  configLoading: boolean;
  configRaw: string;
  configRawOriginal: string;
  configValid: boolean | null;
  configIssues: unknown[];
  configSaving: boolean;
  configApplying: boolean;
  updateRunning: boolean;
  applySessionKey: string;
  configSnapshot: ConfigSnapshot | null;
  configSchema: unknown;
  configSchemaVersion: string | null;
  configSchemaLoading: boolean;
  configUiHints: ConfigUiHints;
  configForm: Record<string, unknown> | null;
  configFormOriginal: Record<string, unknown> | null;
  configFormMode: "form" | "raw";
  configSearchQuery: string;
  configActiveSection: string | null;
  configActiveSubsection: string | null;
  channelsLoading: boolean;
  channelsSnapshot: ChannelsStatusSnapshot | null;
  channelsError: string | null;
  channelsLastSuccess: number | null;
  channelsSelectedChannelId: string | null;
  whatsappLoginMessage: string | null;
  whatsappLoginQrDataUrl: string | null;
  whatsappLoginConnected: boolean | null;
  whatsappBusy: boolean;
  weworkQrModalOpen: boolean;
  weworkQrModalLoading: boolean;
  weworkQrModalPolling: boolean;
  weworkQrModalSuccess: boolean;
  weworkQrModalError: string | null;
  weworkQrModalReplaceWarn: boolean;
  weworkQrModalAuthUrl: string | null;
  weworkQrModalGenPageUrl: string | null;
  weixinQrModalOpen: boolean;
  weixinQrModalLoading: boolean;
  weixinQrModalPolling: boolean;
  weixinQrModalSuccess: boolean;
  weixinQrModalError: string | null;
  weixinQrModalReplaceWarn: boolean;
  weixinQrModalImageSrc: string | null;
  weixinQrModalScanPageUrl: string | null;
  weixinQrModalScanned: boolean;
  weixinQrPollAbort: boolean;
  weixinQrSuccessCloseTimer: number | null;
  weixinQrSessionQrcode: string;
  weixinQrSessionBaseUrl: string;
  weixinQrSessionBotType: string;
  nativeDialog: NativeDialogModel;
  nativePromptInput: string;
  nostrProfileFormState: NostrProfileFormState | null;
  nostrProfileAccountId: string | null;
  configFormDirty: boolean;
  presenceLoading: boolean;
  presenceEntries: PresenceEntry[];
  presenceError: string | null;
  presenceStatus: string | null;
  agentsLoading: boolean;
  agentsList: AgentsListResult | null;
  agentsError: string | null;
  agentsSelectedId: string | null;
  agentsPanel: "overview" | "files" | "tools" | "skills" | "channels" | "cron";
  agentFilesLoading: boolean;
  agentFilesError: string | null;
  agentFilesList: AgentsFilesListResult | null;
  agentFileContents: Record<string, string>;
  agentFileDrafts: Record<string, string>;
  agentFileActive: string | null;
  agentFileSaving: boolean;
  agentIdentityLoading: boolean;
  agentIdentityError: string | null;
  agentIdentityById: Record<string, AgentIdentityResult>;
  agentSkillsLoading: boolean;
  agentSkillsError: string | null;
  agentSkillsReport: SkillStatusReport | null;
  agentSkillsAgentId: string | null;
  sessionsLoading: boolean;
  sessionsResult: SessionsListResult | null;
  sessionEditingKey: string | null;
  /** 消息页侧栏：⋯ 菜单（fixed 浮层，避免被侧栏 overflow 裁剪） */
  sessionOverflow: { top: number; right: number; key: string } | null;
  /** 消息页侧栏：按名称 / 标签字段 / 副标题等模糊过滤会话 */
  sessionSidebarQuery: string;
  sessionsError: string | null;
  sessionsFilterActive: string;
  sessionsFilterLimit: string;
  sessionsIncludeGlobal: boolean;
  sessionsIncludeUnknown: boolean;
  sessionsBulkMode: boolean;
  sessionsSelectedKeys: string[];
  usageLoading: boolean;
  usageResult: SessionsUsageResult | null;
  usageCostSummary: CostUsageSummary | null;
  usageError: string | null;
  usageStartDate: string;
  usageEndDate: string;
  usageSelectedSessions: string[];
  usageSelectedDays: string[];
  usageSelectedHours: number[];
  usageChartMode: "tokens" | "cost";
  usageDailyChartMode: "total" | "by-type";
  usageTimeSeriesMode: "cumulative" | "per-turn";
  usageTimeSeriesBreakdownMode: "total" | "by-type";
  usageTimeSeries: SessionUsageTimeSeries | null;
  usageTimeSeriesLoading: boolean;
  usageSessionLogs: SessionLogEntry[] | null;
  usageSessionLogsLoading: boolean;
  usageSessionLogsExpanded: boolean;
  usageQuery: string;
  usageQueryDraft: string;
  usageQueryDebounceTimer: number | null;
  usageSessionSort: "tokens" | "cost" | "recent" | "messages" | "errors";
  usageSessionSortDir: "asc" | "desc";
  usageRecentSessions: string[];
  usageTimeZone: "local" | "utc";
  usageContextExpanded: boolean;
  usageHeaderPinned: boolean;
  usageSessionsTab: "all" | "recent";
  usageVisibleColumns: string[];
  usageLogFilterRoles: import("./views/usage.js").SessionLogRole[];
  usageLogFilterTools: string[];
  usageLogFilterHasTools: boolean;
  usageLogFilterQuery: string;
  cronLoading: boolean;
  cronJobs: CronJob[];
  cronStatus: CronStatus | null;
  cronError: string | null;
  cronForm: CronFormState;
  cronRunsJobId: string | null;
  cronRuns: CronRunLogEntry[];
  cronBusy: boolean;
  cronAddModalOpen: boolean;
  skillsLoading: boolean;
  skillsReport: SkillStatusReport | null;
  skillsError: string | null;
  skillsFilter: string;
  skillEdits: Record<string, string>;
  skillMessages: Record<string, SkillMessage>;
  skillsBusyKey: string | null;
  skillsAddModalOpen: boolean;
  skillsUploadName: string;
  skillsUploadFiles: File[];
  skillsUploadError: string | null;
  skillsUploadTemplate: string | null;
  skillsUploadBusy: boolean;
  skillsViewMode: "list" | "card";
  skillsSelectedSkillKey: string | null;
  skillsSkillDocContent: string | null;
  skillsSkillDocLoading: boolean;
  skillsSkillDocError: string | null;
  // MCP
  mcpSelectedKey: string | null;
  mcpViewMode: "list" | "card";
  mcpAddModalOpen: boolean;
  mcpAddName: string;
  mcpAddDraft: Record<string, unknown>;
  mcpAddConnectionType: "stdio" | "url" | "service";
  mcpAddEditMode: "form" | "raw";
  mcpAddRawJson: string;
  mcpAddRawError: string | null;
  mcpEditMode: "form" | "raw";
  mcpEditConnectionType: "stdio" | "url" | "service";
  mcpFormDirty: boolean;
  mcpRawJson: string;
  mcpRawError: string | null;
  // LLM Trace
  llmTraceLoading: boolean;
  llmTraceResult: import("./controllers/llm-trace.js").TraceListResult | null;
  llmTraceError: string | null;
  llmTraceMode: "active" | "all";
  llmTraceSearch: string;
  llmTraceEnabled: boolean;
  llmTraceSaving: boolean;
  llmTraceViewContent: string | null;
  llmTraceViewingSessionId: string | null;
  llmTraceViewLoading: boolean;
  // Security (replaces sandbox)
  securityForm: import("./controllers/security.js").SecurityConfigForm | Record<string, unknown> | null;
  // Approvals
  approvalsLoading: boolean;
  approvalsResult: import("./controllers/approvals.js").ApprovalsListResult | null;
  approvalsError: string | null;
  approvalBannerVisible: boolean;
  approvalBannerPollInitialized: boolean;
  approvalBannerBaselineIds: string[];
  approvalBannerPendingCount: number;
  // Models
  modelsSelectedProvider: string | null;
  modelsProviderSearchQuery: string;
  modelsViewMode: "list" | "card";
  modelsFormDirty: boolean;
  modelsAddProviderModalOpen: boolean;
  modelsAddProviderForm: {
    providerId: string;
    displayName: string;
    baseUrl: string;
    apiKey: string;
    apiKeyPrefix: string;
  };
  modelsAddModelModalOpen: boolean;
  modelsAddModelForm: { modelId: string; modelName: string };
  modelsUseModelModalOpen: boolean;
  modelsUseModelModalProvider: string | null;
  modelsSaveError: string | null;
  // Digital employees
  digitalEmployeesLoading: boolean;
  digitalEmployeesError: string | null;
  digitalEmployeesFilter: string;
  digitalEmployeesViewMode: "list" | "card";
  digitalEmployees: {
    id: string;
    name: string;
    description: string;
    prompt?: string;
    enabled?: boolean;
    createdAt?: number;
    builtin: boolean;
    skillIds?: string[];
    skillNames?: string[];
    mcpServerKeys?: string[];
  }[];
  digitalEmployeeCreateModalOpen: boolean;
  digitalEmployeeCreateName: string;
  digitalEmployeeCreateDescription: string;
  digitalEmployeeCreatePrompt: string;
  digitalEmployeeCreateError: string | null;
  digitalEmployeeCreateBusy: boolean;
  digitalEmployeeAdvancedOpen: boolean;
  digitalEmployeeCreateMcpMode: "builder" | "raw";
  digitalEmployeeCreateMcpJson: string;
  digitalEmployeeCreateMcpItems: import("./views/digital-employee.js").EmployeeMcpItem[];
  digitalEmployeeSkillUploadName: string;
  digitalEmployeeSkillUploadFiles: File[];
  digitalEmployeeSkillUploadError: string | null;
  digitalEmployeeSkillUploadBusy: boolean;
  digitalEmployeeEditModalOpen: boolean;
  digitalEmployeeEditId: string;
  digitalEmployeeEditName: string;
  digitalEmployeeEditDescription: string;
  digitalEmployeeEditPrompt: string;
  digitalEmployeeEditMcpJson: string;
  digitalEmployeeEditMcpMode: "builder" | "raw";
  digitalEmployeeEditMcpItems: import("./views/digital-employee.js").EmployeeMcpItem[];
  digitalEmployeeEditSkillNames: string[];
  digitalEmployeeEditSkillFilesToUpload: File[];
  digitalEmployeeEditSkillsToDelete: string[];
  digitalEmployeeEditEnabled: boolean;
  digitalEmployeeEditError: string | null;
  digitalEmployeeEditBusy: boolean;
  // Remote catalogs (employee market / skill library / tool library / tutorials)
  employeeMarketLoadedOnce: boolean;
  employeeMarketLoading: boolean;
  employeeMarketError: string | null;
  employeeMarketQuery: string;
  employeeMarketCategory: string;
  employeeMarketViewMode: "list" | "card";
  employeeMarketItems: import("./controllers/remote-market.ts").EmployeeListItem[];
  employeeMarketSelectedId: number | string | null;
  employeeMarketSelectedDetail: import("./controllers/remote-market.ts").EmployeeDetail | null;
  employeeMarketInstalledRemoteIds: Set<string>;
  employeeMarketRemoteToLocal: Record<string, string>;
  employeeMarketInstallingId: string | null;

  skillLibraryLoadedOnce: boolean;
  skillLibraryLoading: boolean;
  skillLibraryError: string | null;
  skillLibraryQuery: string;
  skillLibraryCategory: string;
  skillLibraryStatus: string;
  skillLibraryItems: import("./controllers/remote-market.ts").SkillListItem[];
  skillLibrarySelectedFolder: string | null;
  skillLibrarySelectedDetail: import("./controllers/remote-market.ts").SkillDetail | null;
  skillLibraryInstallingFolder: string | null;
  skillLibraryInstallSuccess: string | null;

  toolLibraryLoadedOnce: boolean;
  toolLibraryLoading: boolean;
  toolLibraryError: string | null;
  toolLibraryQuery: string;
  toolLibraryCategory: string;
  toolLibraryItems: import("./controllers/remote-market.ts").McpListItem[];
  toolLibrarySelectedId: number | string | null;
  toolLibrarySelectedDetail: import("./controllers/remote-market.ts").McpDetail | null;
  toolLibraryInstalledRemoteIds: Set<string>;
  toolLibraryInstalledMcpMap: Map<number | string, string>;
  toolLibraryInstallingId: number | null;
  toolLibraryMcpEditModalOpen: boolean;
  toolLibraryMcpEditServerKey: string;

  tutorialsLoadedOnce: boolean;
  tutorialsLoading: boolean;
  tutorialsError: string | null;
  tutorialCategories: import("./controllers/remote-market.ts").EduCategory[];
  tutorialsQuery: string;
  tutorialsSelectedCategoryId: number | null;
  tutorialsPlayingLink: string | null;
  aboutUninstallModalOpen: boolean;
  aboutUninstallMode: "program" | "full";
  aboutUninstallLoading: boolean;
  aboutUninstallError: string | null;
  aboutClearWorkspaceLoading: boolean;
  aboutClearWorkspaceError: string | null;
  debugLoading: boolean;
  debugStatus: StatusSummary | null;
  debugHealth: HealthSnapshot | null;
  debugModels: unknown[];
  debugHeartbeat: unknown;
  debugCallMethod: string;
  debugCallParams: string;
  debugCallResult: string | null;
  debugCallError: string | null;
  logsLoading: boolean;
  logsError: string | null;
  logsFile: string | null;
  logsEntries: LogEntry[];
  logsFilterText: string;
  logsLevelFilters: Record<LogLevel, boolean>;
  logsAutoFollow: boolean;
  logsTruncated: boolean;
  logsCursor: number | null;
  logsLastFetchAt: number | null;
  logsLimit: number;
  logsMaxBytes: number;
  logsAtBottom: boolean;
  client: GatewayBrowserClient | null;
  approvalBannerPollInterval: number | null;
  refreshSessionsAfterChat: Set<string>;
  connect: () => void;
  setTab: (tab: Tab) => void;
  setTheme: (theme: ThemeMode, context?: ThemeTransitionContext) => void;
  applySettings: (next: UiSettings) => void;
  loadOverview: () => Promise<void>;
  loadAssistantIdentity: () => Promise<void>;
  loadCron: () => Promise<void>;
  handleWhatsAppStart: (force: boolean) => Promise<void>;
  handleWhatsAppWait: () => Promise<void>;
  handleWhatsAppLogout: () => Promise<void>;
  handleWeWorkQrStart: () => Promise<void>;
  handleWeWorkQrModalClose: () => void;
  handleWeixinQrStart: () => Promise<void>;
  handleWeixinQrModalClose: () => void;
  handleChannelConfigSave: () => Promise<void>;
  handleChannelConfigReload: () => Promise<void>;
  handleNostrProfileEdit: (accountId: string, profile: NostrProfile | null) => void;
  handleNostrProfileCancel: () => void;
  handleNostrProfileFieldChange: (field: keyof NostrProfile, value: string) => void;
  handleNostrProfileSave: () => Promise<void>;
  handleNostrProfileImport: () => Promise<void>;
  handleNostrProfileToggleAdvanced: () => void;
  handleExecApprovalDecision: (decision: "allow-once" | "allow-always" | "deny") => Promise<void>;
  dismissApprovalBanner: () => void;
  handleGatewayUrlConfirm: () => void;
  handleGatewayUrlCancel: () => void;
  handleConfigLoad: () => Promise<void>;
  handleConfigSave: () => Promise<void>;
  handleConfigApply: () => Promise<void>;
  handleConfigFormUpdate: (path: string, value: unknown) => void;
  handleConfigFormModeChange: (mode: "form" | "raw") => void;
  handleConfigRawChange: (raw: string) => void;
  handleInstallSkill: (key: string) => Promise<void>;
  handleUpdateSkill: (key: string) => Promise<void>;
  handleToggleSkillEnabled: (key: string, enabled: boolean) => Promise<void>;
  handleUpdateSkillEdit: (key: string, value: string) => void;
  handleSaveSkillApiKey: (key: string, apiKey: string) => Promise<void>;
  handleCronToggle: (jobId: string, enabled: boolean) => Promise<void>;
  handleCronRun: (jobId: string) => Promise<void>;
  handleCronRemove: (jobId: string) => Promise<void>;
  handleCronAdd: () => Promise<void>;
  handleCronRunsLoad: (jobId: string) => Promise<void>;
  handleCronFormUpdate: (path: string, value: unknown) => void;
  handleSessionsLoad: () => Promise<void>;
  handleSessionsPatch: (key: string, patch: unknown) => Promise<void>;
  handleLoadNodes: () => Promise<void>;
  handleLoadPresence: () => Promise<void>;
  handleLoadSkills: () => Promise<void>;
  handleLoadDebug: () => Promise<void>;
  handleLoadLogs: () => Promise<void>;
  handleDebugCall: () => Promise<void>;
  handleRunUpdate: () => Promise<void>;
  setPassword: (next: string) => void;
  setSessionKey: (next: string) => void;
  setChatMessage: (next: string) => void;
  handleSendChat: (messageOverride?: string, opts?: { restoreDraft?: boolean; refreshSessions?: boolean }) => Promise<void>;
  handleAbortChat: () => Promise<void>;
  removeQueuedMessage: (id: string) => void;
  handleChatScroll: (event: Event) => void;
  resetToolStream: () => void;
  resetChatScroll: () => void;
  exportLogs: (lines: string[], label: string) => void;
  handleLogsScroll: (event: Event) => void;
  handleOpenSidebar: (content: string) => void;
  handleCloseSidebar: () => void;
  handleSplitRatioChange: (ratio: number) => void;
  handleNativePromptInput: (value: string) => void;
  handleNativeDialogConfirm: () => void;
  handleNativeDialogCancel: () => void;
};
